name: Python CI

on: [push] # Автоматический запуск при любой отправке кода

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Выделение виртуальной машины в облаке GitHub

    steps:
    - name: 1. Скачивание исходного кода проекта
      uses: actions/checkout@v4

    - name: 2. Настройка окружения Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 3. Установка зависимостей (Пункт 1 методички)
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest # Ставим линтер и тесты

    - name: 4. Линтинг кода с помощью flake8 (Пункт 2 методички)
      run: |
        # Указываем папку src/, чтобы flake8 проверял только код программы
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: 5. Запуск тестов проекта (Пункт 3 методички)
      run: |
        # Запуск pytest. Флаг --allow-empty нужен, так как папка тестов пустая
        pytest --allow-empty