name: Python CI

on: [push] # Пайплайн запускается автоматически при любой отправке кода

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Выделение виртуальной машины в облаке GitHub

    steps:
    - name: 1. Скачивание исходного кода
      uses: actions/checkout@v4

    - name: 2. Настройка окружения Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 3. Установка зависимостей (П1)
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest # Установка линтера и инструмента для тестов

    - name: 4. Линтинг кода с помощью flake8 (П2)
      run: |
        # Проверяем весь репозиторий на критические синтаксические ошибки
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: 5. Запуск тестов (П3)
      run: |
        # Запуск pytest. Флаг --allow-empty нужен, так как тесты пока пустые
        pytest --allow-empty